sudo: required

services: 
  - docker

before_install:
  - docker build -t balajisundaresan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balajisundaresan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-518345774293"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AccessKey
  secret_access_key:
    secure: "$SecretAccessKey"
