sudo: required

services: 
  - docker

before_install:
  - docker build -t balajisundaresan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balajisundaresan/docker-react npm run test
